spring.application.name=ticket-service

# Neon Connection - note the stringtype=unspecified
spring.datasource.url=jdbc:postgresql://ep-orange-band-ah7cwfnm-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&stringtype=unspecified
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wAjB46oVSTdP

# Hibernate logic
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true